### ISSUE TITLE
http://test.com/profile generates error message

### ISSUE THREAD

**Issue by mgailitis** [openstudioproject/openstudio#158]
If in customer properties set that user Profile is opened after login, it generates error. In user portal pushing Home does the same:
<type 'exceptions.TypeError'> unsupported operand type(s) for -: 'NoneType' and 'long'
Traceback (most recent call last):
  File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "/home/www-data/web2py/applications/openstudion/controllers/profile.py", line 1489, in <module>
  File "/home/www-data/web2py/gluon/globals.py", line 421, in <lambda>
    self._caller = lambda f: f()
  File "/home/www-data/web2py/gluon/tools.py", line 3862, in f
    return action(*a, **b)
  File "/home/www-data/web2py/applications/openstudion/controllers/profile.py", line 45, in index
    classcards = index_get_classcards(customer)
  File "/home/www-data/web2py/applications/openstudion/controllers/profile.py", line 228, in index_get_classcards
    remaining = classcard_get_remaining(row)
  File "/home/www-data/web2py/applications/openstudion/controllers/profile.py", line 592, in classcard_get_remaining
    remaining = total_classes - taken_classes
TypeError: unsupported operand type(s) for -: 'NoneType' and 'long'

**Comment by edwinvandeven** [comment]
Fixed in next release, expected early November.
