### ISSUE TITLE
Fresh install - global DataError<class 'redis.exceptions.DataError'> 

### ISSUE THREAD

**Issue by ciscoterminal** [openstudioproject/openstudio#260]
ALL python libraries are loaded , database is connected, and application is giving this error in web2py and not starting
ERROR SNAPSHOT
<class 'redis.exceptions.DataError'>(Invalid input of type: 'bool'. Convert to a byte, string or number first.)

Traceback (most recent call last):  File "/opt/studio/gluon/main.py", line 461, in wsgibase    session._try_store_in_db(request, response)  File "/opt/studio/gluon/globals.py", line 1239, in _try_store_in_db    record_id = table.insert(**dd)  File "/opt/studio/gluon/contrib/redis_session.py", line 150, in insert    pipe.execute()  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 3443, in execute    return execute(conn, stack, raise_on_error)  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 3309, in _execute_transaction    if EMPTY_RESPONSE not in options])  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 683, in pack_commands    for chunk in self.pack_command(*cmd):  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 659, in pack_command    for arg in imap(self.encoder.encode, args):  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 113, in encode    raise DataError("Invalid input of type: 'bool'. Convert to a "DataError: Invalid input of type: 'bool'. Convert to a byte, string or number first.
-- | --

Redis server status

root@studio:~# sudo netstat -lnp | grep redis
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      23439/redis-server
tcp6       0      0 ::1:6379                :::*                    LISTEN      23439/redis-server

root@studio:~# redis-cli
127.0.0.1:6379> ping
PONG
127.0.0.1:6379>

**Comment by edwinvandeven** [comment]
What version is the redis did you install? The module should be 2.10.6
Version 3 doesn't work (yet).
