### ISSUE TITLE
Registration error

### ISSUE THREAD

**Issue by vpant** [openstudioproject/openstudio#520]
I am using Python 3.8 and Web2Py Version 2.20.4-stable+timestamp.2020.05.03.05.18.50
When someone tries to register the following error occurs although this is not the case when someone changes password through profile or a forgot password request: 

`Traceback (most recent call last):
  File "/home/vasilis/account.indriya.gr/public/gluon/restricted.py", line 219, in restricted
    exec(ccode, environment)

  File "/home/***/***/public/applications/openstudio/controllers/default.py", line 575, in <module>

  File "/home/***/***/public/gluon/globals.py", line 430, in <lambda>
    self._caller = lambda f: f()

  File "/home/***/***/public/applications/openstudio/controllers/default.py", line 142, in user
    form = auth()

  File "/home/***/***/public/gluon/tools.py", line 1801, in __call__
    return getattr(self, args[0])()

  File "/home/***/***/public/gluon/tools.py", line 2989, in register
    if not (self.settings.mailer and self.settings.mailer.send(

  File "/home/***/***/public/gluon/tools.py", line 467, in send
    elif message.strip().startswith('<html') and \

  File "/home/***/***/public/gluon/languages.py", line 419, in __getattr__
    return getattr(str(self), name)

  File "/home/***/***/public/gluon/languages.py", line 389, in __str__
    self.T.translate(self.m, self.s))

  File "/home/***/***/public/gluon/languages.py", line 1013, in translate
    message = self.params_substitution(message, symbols)

  File "/home/***/***/public/gluon/languages.py", line 990, in params_substitution
    #message = message % symbols

ValueError: unsupported format character '!' (0x21) at index 995`

**Comment by vpant** [comment]
It was a email translation issue.
