### ISSUE TITLE
Trouble with web2py-uwsgi-nginx-ubuntu

### ISSUE THREAD

**Issue by stevesanda** [openstudioproject/openstudio#532]
Hello! I've successfully installed Open Studio Project and was able to get it running initially. I've followed the web2py documentation to get nginx and uwsgi running using their preconfigured script. However, when I try and load the openstudio app by browsing to my web server's IP, I get some errors after being redirected to the admin page. 
`````
Error ticket for "openstudio"

<type 'exceptions.ImportError'> No module named applications.openstudio.modules.pytz

Version
web2py™ 2.20.4-stable+timestamp.2020.05.03.05.18.50
Python 2.7.17: /usr/local/bin/uwsgi (prefix: /usr)

Traceback (most recent call last):  
File "/home/www-data/web2py/gluon/restricted.py", line 219, in restricted    exec(ccode, environment)  File "/home/www-data/web2py/applications/openstudio/models/500_os_env.py", line 6, in <module>    import pytz  File "/home/www-data/web2py/gluon/custom_import.py", line 80, in custom_importer    raise ImportError("No module named %s" % modules_prefix)ImportError: No module named applications.openstudio.modules.pytz

Error snapshot
<type 'exceptions.ImportError'>(No module named applications.openstudio.modules.pytz)
File /home/www-data/web2py/gluon/restricted.py in restricted at line 219
File /home/www-data/web2py/applications/openstudio/models/500_os_env.py in <module> at line 6
File /home/www-data/web2py/gluon/custom_import.py in custom_importer at line 80 

Function argument list
(name='pytz', globals={'A': <class 'gluon.html.A'>, 'ANY_OF': <class 'pydal.validators.ANY_OF'>, 'ASSIGNJS': <function ASSIGNJS>, 'B': <class 'gluon.html.B'>, 'BEAUTIFY': <class 'gluon.html.BEAUTIFY'>, 'BODY': <class 'gluon.html.BODY'>, 'BR': <class 'gluon.html.BR'>, 'BUTTON': <class 'gluon.html.BUTTON'>, 'CAT': <class 'gluon.html.CAT'>, 'CENTER': <class 'gluon.html.CENTER'>, ...}, locals={'A': <class 'gluon.html.A'>, 'ANY_OF': <class 'pydal.validators.ANY_OF'>, 'ASSIGNJS': <function ASSIGNJS>, 'B': <class 'gluon.html.B'>, 'BEAUTIFY': <class 'gluon.html.BEAUTIFY'>, 'BODY': <class 'gluon.html.BODY'>, 'BR': <class 'gluon.html.BR'>, 'BUTTON': <class 'gluon.html.BUTTON'>, 'CAT': <class 'gluon.html.CAT'>, 'CENTER': <class 'gluon.html.CENTER'>, ...}, fromlist=None, level=-1)

Code listing
                modules_prefix += "." + itemname
                if result is None:
                    try:
                        result = sys.modules[modules_prefix]
                    except KeyError:
                        raise ImportError("No module named %s" % modules_prefix)
            return result
        else:
            # "from x import a, b, ..."
            pname = "%s.%s" % (modules_prefix, name)

Context
In file: /home/www-data/web2py/applications/openstudio/models/500_os_env.py
`````

Any indicators as to what I can do to get this up and running?

**Comment by stevesanda** [comment]
I started from a fresh VM and forced python3 to be used after finding [this script](https://github.com/arisobel/web2py_scripts/blob/master/setup-web2py-nginx-p3-uwsgi-ubuntu.sh).
