### ISSUE TITLE
Potential MariaDB support?

### ISSUE THREAD

**Issue by Vivi4n** [openstudioproject/openstudio#564]
requirements.txt lists mysqlclient1.4.1 as a default requirement for this, however, it seems to error out upon installation from pip. Would MySQL 5.7 be a necessity to run this, as I don't believe MariaDB is currently supported? (I will give this a potential shot, just wanted to make sure that MariaDB is currently not supported)

```
Collecting mysqlclient==1.4.1
  Using cached mysqlclient-1.4.1.tar.gz (85 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-n4f26xxv/mysqlclient_f265d3c74deb440fae182d3b67023d2d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-n4f26xxv/mysqlclient_f265d3c74deb440fae182d3b67023d2d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-uqzfhy7m
         cwd: /tmp/pip-install-n4f26xxv/mysqlclient_f265d3c74deb440fae182d3b67023d2d/
    Complete output (10 lines):
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-n4f26xxv/mysqlclient_f265d3c74deb440fae182d3b67023d2d/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-n4f26xxv/mysqlclient_f265d3c74deb440fae182d3b67023d2d/setup_posix.py", line 51, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-n4f26xxv/mysqlclient_f265d3c74deb440fae182d3b67023d2d/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/de/d7/919042fb7ed78a89e21c4e43d5daed90d5df18ec183bae3de493a7d9e3ed/mysqlclient-1.4.1.tar.gz#sha256=a62220410e26ce2d2ff94dd0138c3ecfb91db634464a9afb4c8e6b50f0a67e00 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement mysqlclient==1.4.1
ERROR: No matching distribution found for mysqlclient==1.4.1
```

Python version:
`~/openstudio# python3 --version
Python 3.9.2`

MySQL:
`~/openstudio# mysql --version
mysql  Ver 15.1 Distrib 10.5.11-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper`

This is all under Debian 11, using updated repositories.

**Comment by edwinvandeven** [comment]
Currently only MySQL 5.7 is supported. OpenStudio is untested with any MariaDB version. MySQL 8 is known to be incompatible due to slightly out of date MySQL libraries in the web2py framework.
